using Xunit;

namespace SpreadsheetMLReader.Test;

public class ZipFormatTest
{
    [Fact]
    public void ConvertColumnNameToIndexTest()
    {
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("A"), 1);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("B"), 2);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("C"), 3);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("D"), 4);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("E"), 5);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("F"), 6);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("G"), 7);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("H"), 8);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("I"), 9);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("J"), 10);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("K"), 11);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("L"), 12);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("M"), 13);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("N"), 14);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("O"), 15);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("P"), 16);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("Q"), 17);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("R"), 18);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("S"), 19);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("T"), 20);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("U"), 21);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("V"), 22);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("W"), 23);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("X"), 24);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("Y"), 25);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("Z"), 26);

        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("AA"), 27);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("AB"), 28);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("AC"), 29);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("AD"), 30);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("AE"), 31);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("AF"), 32);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("AG"), 33);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("AH"), 34);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("AI"), 35);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("AJ"), 36);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("AK"), 37);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("AL"), 38);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("AM"), 39);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("AN"), 40);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("AO"), 41);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("AP"), 42);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("AQ"), 43);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("AR"), 44);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("AS"), 45);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("AT"), 46);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("AU"), 47);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("AV"), 48);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("AW"), 49);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("AX"), 50);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("AY"), 51);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("AZ"), 52);

        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("BA"), 53);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("BB"), 54);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("BC"), 55);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("BD"), 56);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("BE"), 57);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("BF"), 58);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("BG"), 59);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("BH"), 60);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("BI"), 61);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("BJ"), 62);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("BK"), 63);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("BL"), 64);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("BM"), 65);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("BN"), 66);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("BO"), 67);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("BP"), 68);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("BQ"), 69);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("BR"), 70);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("BS"), 71);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("BT"), 72);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("BU"), 73);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("BV"), 74);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("BW"), 75);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("BX"), 76);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("BY"), 77);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("BZ"), 78);

        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("CA"), 79);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("CB"), 80);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("CC"), 81);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("CD"), 82);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("CE"), 83);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("CF"), 84);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("CG"), 85);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("CH"), 86);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("CI"), 87);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("CJ"), 88);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("CK"), 89);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("CL"), 90);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("CM"), 91);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("CN"), 92);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("CO"), 93);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("CP"), 94);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("CQ"), 95);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("CR"), 96);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("CS"), 97);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("CT"), 98);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("CU"), 99);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("CV"), 100);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("CW"), 101);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("CX"), 102);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("CY"), 103);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("CZ"), 104);

        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("ZA"), 677);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("ZB"), 678);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("ZC"), 679);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("ZD"), 680);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("ZE"), 681);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("ZF"), 682);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("ZG"), 683);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("ZH"), 684);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("ZI"), 685);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("ZJ"), 686);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("ZK"), 687);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("ZL"), 688);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("ZM"), 689);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("ZN"), 690);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("ZO"), 691);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("ZP"), 692);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("ZQ"), 693);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("ZR"), 694);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("ZS"), 695);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("ZT"), 696);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("ZU"), 697);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("ZV"), 698);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("ZW"), 699);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("ZX"), 700);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("ZY"), 701);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("ZZ"), 702);

        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("AAA"), 703);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("AAB"), 704);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("AAC"), 705);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("AAD"), 706);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("AAE"), 707);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("AAF"), 708);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("AAG"), 709);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("AAH"), 710);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("AAI"), 711);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("AAJ"), 712);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("AAK"), 713);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("AAL"), 714);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("AAM"), 715);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("AAN"), 716);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("AAO"), 717);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("AAP"), 718);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("AAQ"), 719);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("AAR"), 720);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("AAS"), 721);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("AAT"), 722);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("AAU"), 723);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("AAV"), 724);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("AAW"), 725);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("AAX"), 726);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("AAY"), 727);
        Assert.Equal(SpreadsheetML.ConvertColumnNameToIndex("AAZ"), 728);
    }

    [Fact]
    public void ConvertColumnIndexToNameTest()
    {
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(1), "A");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(2), "B");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(3), "C");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(4), "D");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(5), "E");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(6), "F");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(7), "G");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(8), "H");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(9), "I");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(10), "J");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(11), "K");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(12), "L");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(13), "M");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(14), "N");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(15), "O");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(16), "P");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(17), "Q");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(18), "R");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(19), "S");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(20), "T");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(21), "U");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(22), "V");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(23), "W");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(24), "X");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(25), "Y");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(26), "Z");

        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(27), "AA");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(28), "AB");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(29), "AC");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(30), "AD");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(31), "AE");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(32), "AF");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(33), "AG");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(34), "AH");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(35), "AI");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(36), "AJ");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(37), "AK");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(38), "AL");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(39), "AM");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(40), "AN");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(41), "AO");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(42), "AP");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(43), "AQ");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(44), "AR");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(45), "AS");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(46), "AT");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(47), "AU");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(48), "AV");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(49), "AW");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(50), "AX");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(51), "AY");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(52), "AZ");

        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(53), "BA");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(54), "BB");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(55), "BC");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(56), "BD");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(57), "BE");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(58), "BF");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(59), "BG");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(60), "BH");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(61), "BI");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(62), "BJ");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(63), "BK");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(64), "BL");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(65), "BM");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(66), "BN");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(67), "BO");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(68), "BP");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(69), "BQ");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(70), "BR");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(71), "BS");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(72), "BT");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(73), "BU");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(74), "BV");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(75), "BW");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(76), "BX");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(77), "BY");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(78), "BZ");

        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(79), "CA");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(80), "CB");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(81), "CC");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(82), "CD");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(83), "CE");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(84), "CF");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(85), "CG");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(86), "CH");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(87), "CI");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(88), "CJ");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(89), "CK");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(90), "CL");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(91), "CM");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(92), "CN");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(93), "CO");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(94), "CP");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(95), "CQ");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(96), "CR");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(97), "CS");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(98), "CT");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(99), "CU");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(100), "CV");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(101), "CW");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(102), "CX");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(103), "CY");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(104), "CZ");

        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(677), "ZA");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(678), "ZB");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(679), "ZC");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(680), "ZD");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(681), "ZE");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(682), "ZF");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(683), "ZG");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(684), "ZH");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(685), "ZI");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(686), "ZJ");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(687), "ZK");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(688), "ZL");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(689), "ZM");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(690), "ZN");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(691), "ZO");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(692), "ZP");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(693), "ZQ");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(694), "ZR");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(695), "ZS");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(696), "ZT");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(697), "ZU");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(698), "ZV");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(699), "ZW");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(700), "ZX");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(701), "ZY");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(702), "ZZ");

        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(703), "AAA");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(704), "AAB");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(705), "AAC");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(706), "AAD");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(707), "AAE");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(708), "AAF");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(709), "AAG");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(710), "AAH");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(711), "AAI");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(712), "AAJ");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(713), "AAK");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(714), "AAL");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(715), "AAM");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(716), "AAN");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(717), "AAO");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(718), "AAP");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(719), "AAQ");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(720), "AAR");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(721), "AAS");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(722), "AAT");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(723), "AAU");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(724), "AAV");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(725), "AAW");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(726), "AAX");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(727), "AAY");
        Assert.Equal(SpreadsheetML.ConvertColumnIndexToName(728), "AAZ");
    }

    [Fact]
    public void ConvertCellAddressTest()
    {
        Assert.Equal(SpreadsheetML.ConvertCellAddress("A123"), (123, 1));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("B123"), (123, 2));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("C123"), (123, 3));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("D123"), (123, 4));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("E123"), (123, 5));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("F123"), (123, 6));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("G123"), (123, 7));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("H123"), (123, 8));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("I123"), (123, 9));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("J123"), (123, 10));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("K123"), (123, 11));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("L123"), (123, 12));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("M123"), (123, 13));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("N123"), (123, 14));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("O123"), (123, 15));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("P123"), (123, 16));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("Q123"), (123, 17));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("R123"), (123, 18));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("S123"), (123, 19));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("T123"), (123, 20));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("U123"), (123, 21));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("V123"), (123, 22));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("W123"), (123, 23));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("X123"), (123, 24));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("Y123"), (123, 25));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("Z123"), (123, 26));

        Assert.Equal(SpreadsheetML.ConvertCellAddress("AA234"), (234, 27));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("AB234"), (234, 28));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("AC234"), (234, 29));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("AD234"), (234, 30));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("AE234"), (234, 31));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("AF234"), (234, 32));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("AG234"), (234, 33));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("AH234"), (234, 34));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("AI234"), (234, 35));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("AJ234"), (234, 36));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("AK234"), (234, 37));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("AL234"), (234, 38));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("AM234"), (234, 39));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("AN234"), (234, 40));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("AO234"), (234, 41));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("AP234"), (234, 42));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("AQ234"), (234, 43));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("AR234"), (234, 44));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("AS234"), (234, 45));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("AT234"), (234, 46));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("AU234"), (234, 47));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("AV234"), (234, 48));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("AW234"), (234, 49));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("AX234"), (234, 50));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("AY234"), (234, 51));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("AZ234"), (234, 52));

        Assert.Equal(SpreadsheetML.ConvertCellAddress("BA345"), (345, 53));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("BB345"), (345, 54));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("BC345"), (345, 55));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("BD345"), (345, 56));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("BE345"), (345, 57));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("BF345"), (345, 58));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("BG345"), (345, 59));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("BH345"), (345, 60));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("BI345"), (345, 61));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("BJ345"), (345, 62));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("BK345"), (345, 63));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("BL345"), (345, 64));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("BM345"), (345, 65));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("BN345"), (345, 66));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("BO345"), (345, 67));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("BP345"), (345, 68));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("BQ345"), (345, 69));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("BR345"), (345, 70));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("BS345"), (345, 71));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("BT345"), (345, 72));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("BU345"), (345, 73));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("BV345"), (345, 74));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("BW345"), (345, 75));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("BX345"), (345, 76));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("BY345"), (345, 77));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("BZ345"), (345, 78));

        Assert.Equal(SpreadsheetML.ConvertCellAddress("CA456"), (456, 79));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("CB456"), (456, 80));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("CC456"), (456, 81));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("CD456"), (456, 82));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("CE456"), (456, 83));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("CF456"), (456, 84));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("CG456"), (456, 85));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("CH456"), (456, 86));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("CI456"), (456, 87));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("CJ456"), (456, 88));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("CK456"), (456, 89));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("CL456"), (456, 90));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("CM456"), (456, 91));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("CN456"), (456, 92));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("CO456"), (456, 93));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("CP456"), (456, 94));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("CQ456"), (456, 95));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("CR456"), (456, 96));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("CS456"), (456, 97));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("CT456"), (456, 98));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("CU456"), (456, 99));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("CV456"), (456, 100));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("CW456"), (456, 101));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("CX456"), (456, 102));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("CY456"), (456, 103));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("CZ456"), (456, 104));

        Assert.Equal(SpreadsheetML.ConvertCellAddress("ZA1"), (1, 677));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("ZB1"), (1, 678));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("ZC1"), (1, 679));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("ZD1"), (1, 680));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("ZE1"), (1, 681));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("ZF1"), (1, 682));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("ZG1"), (1, 683));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("ZH1"), (1, 684));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("ZI1"), (1, 685));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("ZJ1"), (1, 686));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("ZK1"), (1, 687));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("ZL1"), (1, 688));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("ZM1"), (1, 689));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("ZN1"), (1, 690));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("ZO1"), (1, 691));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("ZP1"), (1, 692));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("ZQ1"), (1, 693));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("ZR1"), (1, 694));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("ZS1"), (1, 695));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("ZT1"), (1, 696));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("ZU1"), (1, 697));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("ZV1"), (1, 698));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("ZW1"), (1, 699));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("ZX1"), (1, 700));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("ZY1"), (1, 701));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("ZZ1"), (1, 702));

        Assert.Equal(SpreadsheetML.ConvertCellAddress("AAA987"), (987, 703));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("AAB987"), (987, 704));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("AAC987"), (987, 705));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("AAD987"), (987, 706));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("AAE987"), (987, 707));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("AAF987"), (987, 708));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("AAG987"), (987, 709));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("AAH987"), (987, 710));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("AAI987"), (987, 711));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("AAJ987"), (987, 712));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("AAK987"), (987, 713));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("AAL987"), (987, 714));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("AAM987"), (987, 715));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("AAN987"), (987, 716));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("AAO987"), (987, 717));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("AAP987"), (987, 718));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("AAQ987"), (987, 719));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("AAR987"), (987, 720));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("AAS987"), (987, 721));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("AAT987"), (987, 722));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("AAU987"), (987, 723));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("AAV987"), (987, 724));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("AAW987"), (987, 725));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("AAX987"), (987, 726));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("AAY987"), (987, 727));
        Assert.Equal(SpreadsheetML.ConvertCellAddress("AAZ987"), (987, 728));
    }

    [Fact]
    public void ConvertCellAddress2Test()
    {
        Assert.Equal(SpreadsheetML.ConvertCellAddress(123, 1), "A123");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(123, 2), "B123");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(123, 3), "C123");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(123, 4), "D123");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(123, 5), "E123");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(123, 6), "F123");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(123, 7), "G123");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(123, 8), "H123");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(123, 9), "I123");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(123, 10), "J123");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(123, 11), "K123");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(123, 12), "L123");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(123, 13), "M123");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(123, 14), "N123");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(123, 15), "O123");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(123, 16), "P123");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(123, 17), "Q123");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(123, 18), "R123");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(123, 19), "S123");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(123, 20), "T123");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(123, 21), "U123");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(123, 22), "V123");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(123, 23), "W123");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(123, 24), "X123");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(123, 25), "Y123");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(123, 26), "Z123");

        Assert.Equal(SpreadsheetML.ConvertCellAddress(234, 27), "AA234");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(234, 28), "AB234");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(234, 29), "AC234");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(234, 30), "AD234");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(234, 31), "AE234");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(234, 32), "AF234");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(234, 33), "AG234");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(234, 34), "AH234");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(234, 35), "AI234");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(234, 36), "AJ234");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(234, 37), "AK234");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(234, 38), "AL234");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(234, 39), "AM234");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(234, 40), "AN234");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(234, 41), "AO234");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(234, 42), "AP234");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(234, 43), "AQ234");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(234, 44), "AR234");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(234, 45), "AS234");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(234, 46), "AT234");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(234, 47), "AU234");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(234, 48), "AV234");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(234, 49), "AW234");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(234, 50), "AX234");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(234, 51), "AY234");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(234, 52), "AZ234");

        Assert.Equal(SpreadsheetML.ConvertCellAddress(345, 53), "BA345");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(345, 54), "BB345");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(345, 55), "BC345");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(345, 56), "BD345");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(345, 57), "BE345");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(345, 58), "BF345");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(345, 59), "BG345");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(345, 60), "BH345");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(345, 61), "BI345");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(345, 62), "BJ345");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(345, 63), "BK345");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(345, 64), "BL345");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(345, 65), "BM345");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(345, 66), "BN345");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(345, 67), "BO345");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(345, 68), "BP345");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(345, 69), "BQ345");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(345, 70), "BR345");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(345, 71), "BS345");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(345, 72), "BT345");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(345, 73), "BU345");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(345, 74), "BV345");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(345, 75), "BW345");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(345, 76), "BX345");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(345, 77), "BY345");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(345, 78), "BZ345");

        Assert.Equal(SpreadsheetML.ConvertCellAddress(456, 79), "CA456");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(456, 80), "CB456");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(456, 81), "CC456");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(456, 82), "CD456");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(456, 83), "CE456");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(456, 84), "CF456");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(456, 85), "CG456");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(456, 86), "CH456");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(456, 87), "CI456");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(456, 88), "CJ456");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(456, 89), "CK456");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(456, 90), "CL456");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(456, 91), "CM456");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(456, 92), "CN456");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(456, 93), "CO456");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(456, 94), "CP456");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(456, 95), "CQ456");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(456, 96), "CR456");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(456, 97), "CS456");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(456, 98), "CT456");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(456, 99), "CU456");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(456, 100), "CV456");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(456, 101), "CW456");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(456, 102), "CX456");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(456, 103), "CY456");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(456, 104), "CZ456");

        Assert.Equal(SpreadsheetML.ConvertCellAddress(1, 677), "ZA1");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(1, 678), "ZB1");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(1, 679), "ZC1");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(1, 680), "ZD1");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(1, 681), "ZE1");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(1, 682), "ZF1");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(1, 683), "ZG1");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(1, 684), "ZH1");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(1, 685), "ZI1");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(1, 686), "ZJ1");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(1, 687), "ZK1");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(1, 688), "ZL1");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(1, 689), "ZM1");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(1, 690), "ZN1");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(1, 691), "ZO1");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(1, 692), "ZP1");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(1, 693), "ZQ1");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(1, 694), "ZR1");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(1, 695), "ZS1");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(1, 696), "ZT1");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(1, 697), "ZU1");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(1, 698), "ZV1");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(1, 699), "ZW1");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(1, 700), "ZX1");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(1, 701), "ZY1");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(1, 702), "ZZ1");

        Assert.Equal(SpreadsheetML.ConvertCellAddress(987, 703), "AAA987");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(987, 704), "AAB987");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(987, 705), "AAC987");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(987, 706), "AAD987");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(987, 707), "AAE987");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(987, 708), "AAF987");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(987, 709), "AAG987");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(987, 710), "AAH987");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(987, 711), "AAI987");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(987, 712), "AAJ987");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(987, 713), "AAK987");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(987, 714), "AAL987");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(987, 715), "AAM987");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(987, 716), "AAN987");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(987, 717), "AAO987");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(987, 718), "AAP987");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(987, 719), "AAQ987");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(987, 720), "AAR987");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(987, 721), "AAS987");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(987, 722), "AAT987");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(987, 723), "AAU987");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(987, 724), "AAV987");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(987, 725), "AAW987");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(987, 726), "AAX987");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(987, 727), "AAY987");
        Assert.Equal(SpreadsheetML.ConvertCellAddress(987, 728), "AAZ987");
    }
}
